// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuglWR--RAXxSpOZZn3KY0tWWg36eiSpg',
    appId: '1:734449516669:web:9dac4e22cdae5f3b65b114',
    messagingSenderId: '734449516669',
    projectId: 'times-wire',
    authDomain: 'times-wire.firebaseapp.com',
    storageBucket: 'times-wire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvGk-8I9gQWvKx_vDLCCYy9FNWTkQHLI',
    appId: '1:734449516669:android:a6e0c1b12cafdc1e65b114',
    messagingSenderId: '734449516669',
    projectId: 'times-wire',
    storageBucket: 'times-wire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBraQBk-h9IP-gnFgoDRThfrjrYCW61qv0',
    appId: '1:734449516669:ios:052a423a336103da65b114',
    messagingSenderId: '734449516669',
    projectId: 'times-wire',
    storageBucket: 'times-wire.appspot.com',
    iosClientId: '734449516669-oanm1mmhvfa0k03qs27u0uunsc8mm5ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.timesWire',
  );
}
